/-
C1 — Three VSA operator families, ALL kernel-verified in Lean 4 core (no Mathlib).

  1. MAP  — elementwise (Hadamard) binding. Verified: COMMUTATIVE, exact unbind
            for ±1 roles, distributive. MAP is the commutative contrast operator.
  2. Perm — signed-permutation binding: the swap block T = [[0,1],[1,0]] together
            with the reflection Ref. Verified: orthogonal, exact unbind, and
            order-sensitive WITHIN the family (T·Ref ≠ Ref·T).
  3. EduBind — imported from `EduBindSelfContained` (integer O(2)).

Revision 3 (2026-08-23, audit fix B11). The central negative result is now
stated against EXACTLY the axiom that the positive instances discharge.

  Under Revision 2's specification, whose second binding operation was a free
  field of the structure, a provably commutative binding also satisfied all
  three axioms — the axiom could always be discharged by picking some unrelated
  non-commuting map (Revision 2 used a shear). That loophole is closed:
  `PedagogicalVSA.order_sensitive_ax` now quantifies over two members of the
  declared family `ops`, and `hadFamily_not_order_sensitive` below proves that
  NO family of Hadamard (MAP-style) operators can satisfy it — for any choice of
  index set, any choice of matrices, and any content. That is the machine-checked
  separation between commutative and non-commutative binding.

  Note on the rotation-only case (fix B1): the same negative applies to a family
  of rotations alone, since the rotation group is abelian. That statement is
  proved in full generality over the reals as `EduBind.rot_commutes` in
  src/eduhdc_mathlib/EduBindBlockDiag.lean; it is why the EduBind family here is
  {rotation, reflection} = integer O(2) rather than rotations only.

Honest scope note on "two independent families": in dimension 2 the integer
orthogonal group and the signed-permutation group COINCIDE (both are the
8-element group generated by Rot and Ref), so `edubindVSA` and `permVSA` below
are two different generating sets for the same group, not two independent
operator families. A genuinely independent permutation family requires S₃, i.e.
a 3×3 carrier; that is not formalized here.
-/

import EduBindSelfContained

open Matrix2

-- ---------------------------------------------------------------------------
-- Operator family 2: MAP — elementwise (Hadamard) binding on Fin d → Int
-- ---------------------------------------------------------------------------

/-- Content hypervectors as integer vectors of dimension d. -/
def Vec (d : Nat) : Type := Fin d → Int

/-- Pointwise bundle (addition). -/
def vecAdd (d : Nat) (x y : Vec d) : Vec d := fun i => x i + y i

/-- MAP binding: elementwise multiplication (commutative). -/
def mapBind (d : Nat) (x y : Vec d) : Vec d := fun i => x i * y i

/-- MAP is COMMUTATIVE — the algebraic reason it cannot encode order. -/
theorem map_commutative (d : Nat) (x y : Vec d) :
    mapBind d x y = mapBind d y x := by
  funext i
  dsimp [mapBind]
  rw [Int.mul_comm]

/-- MAP exact unbind: a ±1 role vector is its own inverse under elementwise
    binding (x_i² = 1 pointwise). -/
theorem map_exact_unbind (d : Nat) (x y : Vec d) (h : ∀ i, x i * x i = 1) :
    mapBind d x (mapBind d x y) = y := by
  funext i
  dsimp [mapBind]
  rw [← Int.mul_assoc, h i, Int.one_mul]

/-- MAP binding distributes over bundle. -/
theorem map_distrib (d : Nat) (x y z : Vec d) :
    mapBind d x (vecAdd d y z) = vecAdd d (mapBind d x y) (mapBind d x z) := by
  funext i
  dsimp [mapBind, vecAdd]
  rw [Int.mul_add]

-- ---------------------------------------------------------------------------
-- Contrast theorem A: commutative bind is order-blind at the level of a single
-- bound pair (the classical statement).
-- ---------------------------------------------------------------------------

/-- For a commutative bind, the bound representation of (x, y) and (y, x) is
    IDENTICAL — no measurement can distinguish the two orders. -/
theorem map_order_indistinguishable (d : Nat) (x y : Vec d)
    (measure : Vec d → Int) :
    measure (mapBind d x y) = measure (mapBind d y x) := by
  rw [map_commutative]

/-- Concrete witness that MAP is order-blind even for two distinct vectors:
    with x = [1, 2], y = [3, 5] the two ordered bindings coincide. -/
def vecX : Vec 2 := fun i => if i = ⟨0, by decide⟩ then 1 else 2
def vecY : Vec 2 := fun i => if i = ⟨0, by decide⟩ then 3 else 5

theorem vecX_ne_vecY : vecX ≠ vecY := by
  intro h
  have h0 := congrFun h ⟨0, by decide⟩
  dsimp [vecX, vecY] at h0
  omega

theorem map_order_blind_witness :
    mapBind 2 vecX vecY = mapBind 2 vecY vecX :=
  map_commutative 2 vecX vecY

-- ---------------------------------------------------------------------------
-- Contrast theorem B (fix B11): a commutative bind cannot satisfy the
-- PedagogicalVSA order-sensitivity axiom, stated on the SAME carrier and the
-- SAME axiom shape that `edubindVSA` and `permVSA` discharge.
-- ---------------------------------------------------------------------------

/-- Hadamard (elementwise) product on the 2×2 carrier — MAP lifted to the
    carrier the positive instances use, so the comparison is apples to apples. -/
def had (M N : Matrix2 Int) : Matrix2 Int :=
  { a00 := M.a00 * N.a00, a01 := M.a01 * N.a01,
    a10 := M.a10 * N.a10, a11 := M.a11 * N.a11 }

private theorem int_swap (a b y : Int) : a * (b * y) = b * (a * y) := by
  rw [← Int.mul_assoc, ← Int.mul_assoc, Int.mul_comm a b]

/-- ANY two Hadamard binding operations commute, whatever matrices they use. -/
theorem had_ops_commute (M N Y : Matrix2 Int) :
    had M (had N Y) = had N (had M Y) := by
  ext <;> dsimp [had] <;> exact int_swap _ _ _

/-- THE NEGATIVE RESULT. No family of Hadamard (MAP-style) binding operations
    can satisfy `PedagogicalVSA.order_sensitive_ax`: for every index family
    `Ms`, every pair of indices, and every content, the two orders agree. This
    holds for an arbitrary index family, so it is not escapable by enlarging
    the operator set — unlike Revision 2, where a free second operation made
    the axiom satisfiable by a commutative binding. -/
theorem hadFamily_not_order_sensitive (Ms : Nat → Matrix2 Int) :
    ¬ (∃ i j Y, had (Ms i) (had (Ms j) Y) ≠ had (Ms j) (had (Ms i) Y)) := by
  intro h; obtain ⟨i, j, Y, hne⟩ := h
  exact hne (had_ops_commute (Ms i) (Ms j) Y)

/-- Corollary in the form used by the paper: a Hadamard family satisfies
    Axioms 1 and 3 (see `map_exact_unbind`, `map_distrib`) yet provably fails
    Axiom 2, so Axiom 2 is exactly what separates the two operator classes. -/
theorem had_fails_only_axiom_two (Ms : Nat → Matrix2 Int) (i j : Nat) (Y : Matrix2 Int) :
    had (Ms i) (had (Ms j) Y) = had (Ms j) (had (Ms i) Y) :=
  had_ops_commute (Ms i) (Ms j) Y

/-- IMPOSSIBILITY THEOREM (the fix for B11, stated positively). No
    `PedagogicalVSA` can have a Hadamard (MAP-style) binding family at all: the
    order-sensitivity axiom is contradictory with elementwise binding. Under the
    Revision-2 specification this was FALSE — a Hadamard family satisfied every
    axiom by borrowing an unrelated non-commuting second operation. -/
theorem no_hadamard_PedagogicalVSA
    (P : PedagogicalVSA (Matrix2 Int)) (Ms : Nat → Matrix2 Int)
    (hops : ∀ i, P.ops i = had (Ms i)) : False := by
  obtain ⟨i, j, Y, hne⟩ := P.order_sensitive_ax
  rw [hops i, hops j] at hne
  exact hadFamily_not_order_sensitive Ms ⟨i, j, Y, hne⟩

/-- EduBind, in contrast, DOES distinguish order, with both witnesses drawn
    from its own family (imported theorem): Rot·Ref ≠ Ref·Rot. -/
theorem edubind_order_sensitive : Rot.mul Ref ≠ Ref.mul Rot := Rot_Ref_non_commutative

-- ---------------------------------------------------------------------------
-- Operator family 3: Perm — signed permutations, generated by the swap block
-- and the reflection. Order-sensitive within the family.
-- ---------------------------------------------------------------------------

/-- The swap block: permutation matrix T = [[0,1],[1,0]]. -/
def T : Matrix2 Int := { a00 := 0, a01 := 1, a10 := 1, a11 := 0 }

/-- T is an involution: T² = I. -/
theorem T_involution : T.mul T = Matrix2.one := by
  ext <;> dsimp [mul, T, one] <;> omega

/-- T is orthogonal: Tᵀ T = I. -/
theorem T_orthogonal : (T.transpose).mul T = Matrix2.one := by
  ext <;> dsimp [mul, transpose, T, one] <;> omega

/-- Perm exact unbind for the swap block: because T² = I, binding twice by T
    recovers the content exactly (∀ Y). -/
theorem T_exact_unbind (Y : Matrix2 Int) : T.mul (T.mul Y) = Y := by
  ext <;> dsimp [mul, T] <;> omega

/-- Exact unbind for the swap block in transpose form, matching the shape of
    `PedagogicalVSA.inv`. -/
theorem T_exact_unbind_transpose (Y : Matrix2 Int) :
    (T.transpose).mul (T.mul Y) = Y := by
  ext <;> dsimp [mul, transpose, T] <;> omega

/-- Perm binding distributes over bundle. -/
theorem T_bundle_distrib (A Z : Matrix2 Int) :
    T.mul (A.add Z) = (T.mul A).add (T.mul Z) := by
  ext <;> dsimp [mul, add, T] <;> omega

/-- Axiom 2 for Perm, INTRA-FAMILY: the swap block and the reflection block are
    both signed permutations, and they do not commute. -/
theorem T_Ref_non_commutative : T.mul Ref ≠ Ref.mul T := by
  intro h
  have h01 : (T.mul Ref).a01 = (Ref.mul T).a01 := congrArg Matrix2.a01 h
  dsimp [mul, T, Ref] at h01
  omega

/-- Axiom 2 for Perm at the level of binding OPERATIONS. -/
theorem lmul_T_Ref_non_comm :
    ∃ Y, lmul T (lmul Ref Y) ≠ lmul Ref (lmul T Y) := by
  refine ⟨Matrix2.one, ?_⟩
  intro h
  have h01 := congrArg Matrix2.a01 h
  dsimp [lmul, mul, one, T, Ref] at h01
  omega

/-- The Perm generator family: index 0 is the swap block, every other index is
    the reflection. Both are signed permutations, hence orthogonal. -/
def permGen : Nat → Matrix2 Int
  | 0 => T
  | _ => Ref

/-- Perm is a PedagogicalVSA under the Revision-3 (intra-family) specification. -/
def permVSA : PedagogicalVSA (Matrix2 Int) where
  bundle := fun X Y => X.add Y
  ops := fun i => lmul (permGen i)
  inv := fun i => lmul (permGen i).transpose
  exact_unbind_ax := by
    intro i Y
    cases i with
    | zero   => exact T_exact_unbind_transpose Y
    | succ _ => exact Ref_exact_unbind Y
  bundle_distrib_ax := by
    intro i X Y
    cases i with
    | zero   => exact T_bundle_distrib X Y
    | succ _ => exact Ref_bundle_distrib X Y
  order_sensitive_ax := by
    obtain ⟨Y, hY⟩ := lmul_T_Ref_non_comm
    exact ⟨0, 1, Y, hY⟩

/-- The library provides two first-class verified pedagogical operators under
    the intra-family specification. (See the header note: in dimension 2 these
    are two generating sets for the same group, not two independent families.) -/
def verifiedOperators : List (PedagogicalVSA (Matrix2 Int)) :=
  [edubindVSA, permVSA]

theorem verifiedOperators_count : verifiedOperators.length = 2 := by rfl
